[tool.black]

line-length = 120
skip-string-normalization = true
target-version = ['py38']

[tool.isort]

force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true